[pytest]

addopts =
    -v
    --tb=short
    --maxfail=5
    --alluredir=./reports/allure_report
    --clean-alluredir
    --reruns=2
    --reruns-delay=1

markers =
    smoke: smoke test
    regression: regression test
    login: login test

testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*

disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True