[pytest]

addopts = -v -s --alluredir=./reports/allure_report --clean-alluredir

markers =
    smoke: smoke test
    regression: regression test
    login: login test

disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True